ci: use gradle wrapper in ci per https://github.com/gradle/actions (#100)
I noticed builds started failing like this in #99:

```
Run gradle/actions/setup-gradle@v4
Merged default JDK locations into /home/runner/.m2/toolchains.xml
Restore Gradle state from cache
All Gradle Wrapper jars are valid
Error: SyntaxError: Unexpected token '<', "<html>
<he"... is not valid JSON
SyntaxError: Unexpected token '<', "<html>
<he"... is not valid JSON
    at JSON.parse (<anonymous>)
    at httpGetGradleVersions (/home/runner/work/_actions/gradle/actions/v4/dist/setup-gradle/main/index.js:159204:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async findGradleVersionDeclaration (/home/runner/work/_actions/gradle/actions/v4/dist/setup-gradle/main/index.js:159112:28)
    at async gradleRelease (/home/runner/work/_actions/gradle/actions/v4/dist/setup-gradle/main/index.js:159102:25)
    at async installGradle (/home/runner/work/_actions/gradle/actions/v4/dist/setup-gradle/main/index.js:159063:25)
    at async Object.provisionGradle (/home/runner/work/_actions/gradle/actions/v4/dist/setup-gradle/main/index.js:159054:26)
    at async run (/home/runner/work/_actions/gradle/actions/v4/dist/setup-gradle/main/index.js:155979:9)
```

Instead of downloading gradle, let's just use the one checked in to the
repo.